name: Salmonella_Gene_Summary_Pipeline
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - python=3.9
 - sra-tools
 - seqkit
 - trimmomatic
 - skesa
 - blast
 - ncbi-datasets-cli
 - entrez-direct
